### ISSUE TITLE
Ask about "key" in Replay Buffer - keyA and keyB

### ISSUE THREAD

**Issue by realjoenguyen** [AutonomousAgentsLab/cr-dv3#2]
Hi authors, 

What is `keyA` and `keyB` in the implementation? Why we need to split the original `key = sample.info.key` into `self.step_to_keyA` and `self.step_to_keyB`? 

Thank you !

**Comment by doylech** [comment]
When we sample from reverb, we receive a key that we need to use later to update the priority of the item. JAX by default only uses 32-bit dtypes and the key from reverb is 64 bits. So, we split the key we receive, store the two parts, then recombine them to make the update.
